config/routes.rb
Rails.application.routes.draw do
  resources :currency_conversions, path: "conversions" do
    collection do
      get "all"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "currency_conversions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency_conversion.rb
class CurrencyConversion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/currency_conversions_controller.rb
require_dependency "currency_converter"

class CurrencyConversionsController < ApplicationController
  include CurrencyConverter
  before_action :set_currency_conversion, only: %i[ show edit update destroy ]

  # GET /currency_conversions or /currency_conversions.json
  def index
    @currency_conversions = CurrencyConversion.all
    @currency_conversion = CurrencyConversion.new
    @currencies = get_currencies
  end

  # GET /currency_conversions/all
  def all
    @currency_conversions = CurrencyConversion.all
  end

  # GET /currency_conversions/1 or /currency_conversions/1.json
  def show
  end

  # GET /currency_conversions/new
  def new
    @currency_conversion = CurrencyConversion.new
    @currencies = get_currencies
  end

  # GET /currency_conversions/1/edit
  def edit
     @currencies = get_currencies
     @selected_from_currency = @currency_conversion.from
     @selected_to_currency = @currency_conversion.to
  end

  # POST /currency_conversions or /currency_conversions.json
  def create
    # Calculate conversion amount
    conversion_amount = convert(currency_conversion_params[:amount], currency_conversion_params[:from], currency_conversion_params[:to])

    @currency_conversion = CurrencyConversion.new(currency_conversion_params)
    @currency_conversion.conversion_amount = conversion_amount

    respond_to do |format|
      if @currency_conversion.save
        format.html { redirect_to @currency_conversion, notice: "Currency conversion was successfully created." }
        format.json { render :show, status: :created, location: @currency_conversion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @currency_conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currency_conversions/1 or /currency_conversions/1.json
  def update
    conversion_amount = convert(currency_conversion_params[:amount], currency_conversion_params[:from], currency_conversion_params[:to])
    respond_to do |format|
      if @currency_conversion.update(currency_conversion_params.merge(conversion_amount: conversion_amount))
        format.html { redirect_to @currency_conversion, notice: "Currency conversion was successfully updated." }
        format.json { render :show, status: :ok, location: @currency_conversion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @currency_conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currency_conversions/1 or /currency_conversions/1.json
  def destroy
    @currency_conversion.destroy!

    respond_to do |format|
      format.html { redirect_to currency_conversions_path, status: :see_other, notice: "Currency conversion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency_conversion
      @currency_conversion = CurrencyConversion.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def currency_conversion_params
      params.expect(currency_conversion: [ :amount, :from, :to, :conversion_amount ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_conversions_helper.rb
module CurrencyConversionsHelper
end

app/views/currency_conversions/_currency_conversion.html.erb
<div id="<%= dom_id currency_conversion %>">
  <p>
    <strong>Amount:</strong>
    <%= currency_conversion.amount %>
  </p>

  <p>
    <strong>From:</strong>
    <%= currency_conversion.from %>
  </p>

  <p>
    <strong>To:</strong>
    <%= currency_conversion.to %>
  </p>

  <p>
    <strong>Conversion amount:</strong>
    <%= currency_conversion.conversion_amount %>
  </p>
  
  <p>
    <strong>Created at:</strong>
    <%= currency_conversion.created_at %>
  </p>
  
  <p>
    <strong>Last updated at:</strong>
    <%= currency_conversion.updated_at %>
  </p>

</div>

app/views/currency_conversions/_form.html.erb
<%= form_with(model: currency_conversion) do |form| %>
  <% if currency_conversion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(currency_conversion.errors.count, "error") %> prohibited this currency_conversion from being saved:</h2>

      <ul>
        <% currency_conversion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :from, style: "display: block" %>
    <%= form.text_field :from %>
  </div>

  <div>
    <%= form.label :to, style: "display: block" %>
    <%= form.text_field :to %>
  </div>

  <div>
    <%= form.label :conversion_amount, style: "display: block" %>
    <%= form.text_field :conversion_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/currency_conversions/_form_fields.html.erb
<div class="col-2">
<%= form.label :amount, "Amount", class: "mb-3" %><br>
<%= form.number_field :amount, step: 0.01, class: "form-control", required: true %>
</div>

<div class="col-2">
<%= form.label :from, "From Currency", class: "mb-3" %><br>
<%= form.select :from, options_for_select(@currencies), {}, class: "form-control" %>
</div>

<div class="col-2">
<%= form.label :to, "To Currency", class: "mb-3" %><br>
<%= form.select :to, options_for_select(@currencies), {}, class: "form-control" %>
</div>

app/views/currency_conversions/all.html.erb
<div class="all-new">
    <%= link_to "New currency conversion", root_path, class: "btn btn-success btn-lg" %>
</div>

<div id="currency_conversions" class="page-all">
    <div class="all-currencies">
    <% @currency_conversions.each do |currency_conversion| %>
        <div class="card" style="width: 18rem;">
            <div class="card-body all-conversion">
                <span class="card-title mb-2"><b>Amount:</b> <%= currency_conversion.amount %></span>
                <span class="card-title mb-2"><b>From Currency:</b> <%= currency_conversion.from %></span>
                <span class="card-title mb-2"><b>To Currency:</b>  <%= currency_conversion.to %></span>
                <%= link_to "View", currency_conversion, class: 'btn btn-primary' %>
            </div>
        </div>
        <p>
        </p>
    <% end %>

    </div>
</div>

app/views/currency_conversions/edit.html.erb
<% content_for :title, "Editing currency conversion" %>

<h1>Editing currency conversion</h1>

<%= form_with model: @currency_conversion, local: true do |form| %>
  <%= render "form_fields", form: form %>
  <div>
    <%= form.submit "Update conversion", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this currency conversion", @currency_conversion %> |
  <%= link_to "Back to currency conversions", root_path %>
</div>

app/views/currency_conversions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Currency Converter" %>

<div class="container-fluid hero">
  <div class="text-center mb-5">
    <h1 class="mb-4">Currency Converter</h1>
    <p class="fs-5">Convert between multiple currencies in an <b class="text-success">instant!</b></p>
  </div>

  <%= form_with model: @currency_conversion, local: true, html: {class: "hero-form shadow-lg rounded" } do |form|%>
    <div class="row w-full mb-5 hero-form-content">
      <%= render "form_fields", form: form %>
    </div>
    <div>
      <%= form.submit "Convert", class: "btn btn-primary btn-lg" %>
    </div>
<% end %>
</div>

app/views/currency_conversions/new.html.erb
<% content_for :title, "New Currency Conversion" %>

<h1>New Currency Conversion</h1>

<%= form_with model: @currency_conversion, local: true do |form| %>
  <div>
    <%= form.label :amount, "Amount" %><br>
    <%= form.number_field :amount, step: 0.01, class: "form-control", required: true %>
  </div>

  <div>
    <%= form.label :from, "From Currency" %><br>
    <%= form.select :from, options_for_select(@currencies), {}, class: "form-control" %>
  </div>

  <div>
    <%= form.label :to, "To Currency" %><br>
    <%= form.select :to, options_for_select(@currencies), {}, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Convert", class: "btn btn-primary" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to Currency Conversions", currency_conversions_path, class: "btn btn-secondary" %>
</div>

app/views/currency_conversions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @currency_conversion %>

<div>
  <%= link_to "Edit this currency conversion", edit_currency_conversion_path(@currency_conversion) %> |
  <%= link_to "Back to currency conversions", all_currency_conversions_path %>

  <%= button_to "Delete", @currency_conversion, method: :delete, class: 'mt-3 btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Currency Converter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-primary p-3 mb-5" data-bs-theme="dark">
  <div class="container-fluid">
      <%= link_to "Currency Converter", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All Conversions", all_currency_conversions_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <div class="wrapper-container">
    <%= yield %>
  </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</html>